modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="mc_official_site_collector"
version="${file.jarVersion}"
displayName="MC Official Site Collector"
authors="示例服务器"
description='''将服务器实时状态与原版玩家统计安全同步到网站。'''

[[dependencies.mc_official_site_collector]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="SERVER"

[[dependencies.mc_official_site_collector]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1]"
ordering="NONE"
side="SERVER"