<?php
declare(strict_types=1);
require_once __DIR__.'/../统一认证/main_database.php';
function plan_db():PDO{static $pdo=null;if($pdo instanceof PDO)return $pdo;$c=site_main_database_config();$pdo=new PDO(site_main_database_dsn($c),(string)$c['username'],(string)$c['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC,PDO::ATTR_EMULATE_PREPARES=>false]);plan_initialize($pdo);return $pdo;}
function plan_initialize(PDO $pdo):void{
 $legacy=$pdo->query("SHOW TABLES LIKE 'plan_materials'")->fetchColumn();
 if($legacy){$cols=$pdo->query('SHOW COLUMNS FROM plan_materials')->fetchAll(PDO::FETCH_COLUMN);if(!in_array('litematic_id',$cols,true)){$count=(int)$pdo->query('SELECT COUNT(*) FROM plan_materials')->fetchColumn()+(int)$pdo->query('SELECT COUNT(*) FROM plan_projects')->fetchColumn();if($count>0)throw new RuntimeException('检测到旧版计划表数据，请先迁移');$pdo->exec('SET FOREIGN_KEY_CHECKS=0;DROP TABLE IF EXISTS plan_claims;DROP TABLE IF EXISTS plan_materials;DROP TABLE IF EXISTS plan_projects;SET FOREIGN_KEY_CHECKS=1');}}
 $pdo->exec("CREATE TABLE IF NOT EXISTS plan_projects(id VARCHAR(32) PRIMARY KEY,name VARCHAR(80) NOT NULL,description VARCHAR(240) NOT NULL DEFAULT '',about TEXT NOT NULL,status ENUM('active','paused','completed') NOT NULL DEFAULT 'active',owner_username VARCHAR(64) NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,INDEX idx_plan_updated(updated_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS plan_litematics(id VARCHAR(32) PRIMARY KEY,project_id VARCHAR(32) NOT NULL,filename VARCHAR(180) NOT NULL,total_types INT UNSIGNED NOT NULL,total_blocks BIGINT UNSIGNED NOT NULL,created_at DATETIME NOT NULL,CONSTRAINT fk_litematic_project FOREIGN KEY(project_id) REFERENCES plan_projects(id) ON DELETE CASCADE,INDEX idx_litematic_project(project_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS plan_materials(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,litematic_id VARCHAR(32) NOT NULL,block_id VARCHAR(160) NOT NULL,display_name VARCHAR(160) NOT NULL,block_count BIGINT UNSIGNED NOT NULL,boxes DECIMAL(10,3) NOT NULL,stacks DECIMAL(10,3) NOT NULL,CONSTRAINT fk_material_litematic FOREIGN KEY(litematic_id) REFERENCES plan_litematics(id) ON DELETE CASCADE,UNIQUE KEY uq_litematic_block(litematic_id,block_id),INDEX idx_material_litematic(litematic_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS plan_claims(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,project_id VARCHAR(32) NOT NULL,litematic_id VARCHAR(32) NOT NULL,material_id BIGINT UNSIGNED NOT NULL,claimant VARCHAR(64) NOT NULL,boxes DECIMAL(10,3) NOT NULL,collected_at DATETIME NULL,created_at DATETIME NOT NULL,CONSTRAINT fk_claim_project FOREIGN KEY(project_id) REFERENCES plan_projects(id) ON DELETE CASCADE,CONSTRAINT fk_claim_litematic FOREIGN KEY(litematic_id) REFERENCES plan_litematics(id) ON DELETE CASCADE,CONSTRAINT fk_claim_material FOREIGN KEY(material_id) REFERENCES plan_materials(id) ON DELETE CASCADE,INDEX idx_claim_project(project_id),INDEX idx_claim_material(material_id),INDEX idx_claimant(claimant)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS plan_members(project_id VARCHAR(32) NOT NULL,username VARCHAR(64) NOT NULL,role ENUM('owner','admin','member') NOT NULL DEFAULT 'member',joined_at DATETIME NOT NULL,PRIMARY KEY(project_id,username),CONSTRAINT fk_member_project FOREIGN KEY(project_id) REFERENCES plan_projects(id) ON DELETE CASCADE,INDEX idx_plan_member_user(username)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
 $pdo->exec("CREATE TABLE IF NOT EXISTS plan_profiles(username VARCHAR(64) PRIMARY KEY,nickname VARCHAR(64) NOT NULL DEFAULT '',minecraft_username VARCHAR(16) NOT NULL DEFAULT '',updated_at DATETIME NOT NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
}
function plan_projects(PDO $pdo):array{return $pdo->query("SELECT p.*,(SELECT nickname FROM plan_profiles pf WHERE pf.username=p.owner_username) owner_nickname,(SELECT minecraft_username FROM plan_profiles pf WHERE pf.username=p.owner_username) owner_minecraft,(SELECT COUNT(*) FROM plan_litematics l WHERE l.project_id=p.id) litematic_count,(SELECT COALESCE(SUM(l.total_blocks),0) FROM plan_litematics l WHERE l.project_id=p.id) total_blocks,(SELECT COALESCE(SUM(m.boxes),0) FROM plan_materials m JOIN plan_litematics l ON l.id=m.litematic_id WHERE l.project_id=p.id) total_boxes,(SELECT COALESCE(SUM(c.boxes),0) FROM plan_claims c WHERE c.project_id=p.id) claimed_boxes,(SELECT COALESCE(SUM(c.boxes),0) FROM plan_claims c WHERE c.project_id=p.id AND c.collected_at IS NOT NULL) collected_boxes,(SELECT COUNT(*) FROM plan_claims c WHERE c.project_id=p.id) claim_count FROM plan_projects p ORDER BY p.updated_at DESC")->fetchAll();}
function plan_project(PDO $pdo,string $id):?array{
 $s=$pdo->prepare('SELECT * FROM plan_projects WHERE id=?');$s->execute([$id]);$p=$s->fetch();if(!$p)return null;
 $s=$pdo->prepare("SELECT * FROM plan_members WHERE project_id=? ORDER BY FIELD(role,'owner','admin','member'),username");$s->execute([$id]);$p['members']=$s->fetchAll();
 $s=$pdo->prepare('SELECT * FROM plan_litematics WHERE project_id=? ORDER BY created_at');$s->execute([$id]);$p['litematics']=$s->fetchAll();
 $m=$pdo->prepare("SELECT m.*,COALESCE((SELECT SUM(c.boxes) FROM plan_claims c WHERE c.material_id=m.id),0) claimed_boxes,COALESCE((SELECT SUM(c.boxes) FROM plan_claims c WHERE c.material_id=m.id AND c.collected_at IS NOT NULL),0) collected_boxes FROM plan_materials m WHERE m.litematic_id=? ORDER BY m.block_count DESC");
 $c=$pdo->prepare('SELECT * FROM plan_claims WHERE litematic_id=? ORDER BY created_at DESC');foreach($p['litematics'] as &$l){$m->execute([$l['id']]);$l['materials']=$m->fetchAll();$c->execute([$l['id']]);$l['claims']=$c->fetchAll();}return $p;
}
function plan_user_claims(PDO $pdo,string $username):array{$s=$pdo->prepare('SELECT c.*,p.name project_name,m.display_name,m.block_id,l.filename FROM plan_claims c JOIN plan_projects p ON p.id=c.project_id JOIN plan_materials m ON m.id=c.material_id JOIN plan_litematics l ON l.id=c.litematic_id WHERE c.claimant=? ORDER BY c.created_at DESC');$s->execute([$username]);return $s->fetchAll();}

function plan_profile(PDO $pdo,string $username):array{$s=$pdo->prepare('SELECT * FROM plan_profiles WHERE username=?');$s->execute([$username]);return $s->fetch()?:['username'=>$username,'nickname'=>'','minecraft_username'=>'','updated_at'=>null];}
