<?php
declare(strict_types=1);
require __DIR__.'/db.php';require_once __DIR__.'/../统一认证/auth.php';
$user=auth_is_authenticated()?auth_current_user():null;$csrf=auth_csrf_token();
$error='';try{$projects=plan_projects(plan_db());}catch(Throwable $e){error_log('Plan index: '.$e->getMessage());$projects=[];$error='计划表初始化失败，错误已写入服务器日志。';}
function h(string $v):string{return htmlspecialchars($v,ENT_QUOTES,'UTF-8');}
function status_name(string $s):string{return ['active'=>'进行中','paused'=>'已暂停','completed'=>'已完成'][$s]??$s;}
$active=count(array_filter($projects,fn($p)=>$p['status']==='active'));
?><!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><meta name="theme-color" content="#f9a8d4"><meta name="description" content="Minecraft 建筑投影、材料统计与协作认领"><title>计划表 | 示例服务器</title><link rel="stylesheet" href="../assets/site.css?v=20260731a"><script src="/assets/lenis.min.js?v=1.3.25"></script><script src="/assets/site-config.php?v=20260724a"></script><script src="../assets/site.js?v=20260731a"></script></head>
<body class="plans-page"><header class="topbar"><div class="shell"><a class="brand" href="../">示例服务器</a><nav class="nav" aria-label="站点导航"><a href="../">首页</a><a href="../状态/">实时状态</a><a href="../统计数据/">玩家统计</a><a href="../配方/">配方</a><a href="../附魔计算/">附魔计算</a><a href="../经纬度/">经纬度</a><a href="./" aria-current="page">计划表</a><?php if($user):?><?php if(auth_is_superadmin()):?><a class="nav-account" href="/admin/">后台</a><?php endif;?><a href="/个人资料/">个人资料</a><form class="machine-logout" method="post" action="/统一认证/logout.php"><input type="hidden" name="next" value="/计划表/"><input type="hidden" name="csrf_token" value="<?=h($csrf)?>"><button type="submit">退出</button></form><?php endif;?></nav></div></header>
<main class="shell plans-main"><section class="plans-heading"><div><p class="plans-kicker">LITETRACK / PHP EDITION</p><h1>建筑计划</h1><p class="plans-lede">上传 Litematica 投影，拆解材料总量，按盒认领并跟踪收集状态。</p></div><?php if($user):?><div class="plan-heading-actions"><a href="/个人资料/">个人资料</a><a href="claims.php">我的认领</a><?php if(auth_is_site_admin()):?><button class="plans-primary" data-create-open>新建项目</button><?php endif;?></div><?php else:?><a class="plans-primary" href="<?=h(auth_login_url('/计划表/'))?>">统一认证</a><?php endif;?></section>
<section class="plans-summary"><div><span>进行中</span><strong><?=$active?></strong></div><div><span>全部项目</span><strong><?=count($projects)?></strong></div><div><span>投影文件</span><strong><?=array_sum(array_map(fn($p)=>(int)$p['litematic_count'],$projects))?></strong></div></section>
<section class="plans-toolbar"><div class="plans-tabs"><button class="active" data-filter="all">全部</button><button data-filter="active">进行中</button><button data-filter="paused">已暂停</button><button data-filter="completed">已完成</button></div><label class="plans-search"><span>搜索项目</span><input data-search type="search" placeholder="名称、描述或发起人"></label></section>
<?php if($error):?><section class="plan-empty" role="alert"><?=h($error)?></section><?php endif;?>
<section class="plans-grid" data-grid><?php foreach($projects as $p):$total=(float)$p['total_boxes'];$claimed=(float)$p['claimed_boxes'];$collected=(float)$p['collected_boxes'];$claimProgress=$total>0?(int)round(min(1,$claimed/$total)*100):0;$collectProgress=$claimed>0?(int)round(min(1,$collected/$claimed)*100):0;?><a class="plan-card" href="project.php?id=<?=h($p['id'])?>" data-status="<?=h($p['status'])?>" data-search="<?=h(strtolower($p['name'].' '.$p['description'].' '.$p['owner_username']))?>"><div class="plan-card-head"><span class="plan-status <?=h($p['status'])?>"><?=status_name($p['status'])?></span><span class="plan-updated"><?=h(substr($p['updated_at'],0,10))?></span></div><h2><?=h($p['name'])?></h2><p><?=h($p['description']?:'暂无项目说明')?></p><div class="plan-progress"><div class="plan-progress-label"><span>认领进度</span><strong><?=$claimProgress?>%</strong></div><div class="plan-progress-bar"><i style="width:<?=$claimProgress?>%"></i></div></div><?php if($claimed>0):?><div class="plan-progress collected"><div class="plan-progress-label"><span>收集完成</span><strong><?=$collectProgress?>%</strong></div><div class="plan-progress-bar"><i style="width:<?=$collectProgress?>%"></i></div></div><?php endif;?><div class="plan-card-stats"><span><b><?=(int)$p['litematic_count']?></b> 投影</span><span><b><?=number_format((int)$p['total_blocks'])?></b> 方块</span><span><b><?=(int)$p['claim_count']?></b> 认领</span></div><div class="plan-card-foot"><span class="plan-owner"><img src="asset.php?kind=avatar&amp;name=<?=rawurlencode($p['owner_minecraft']?:$p['owner_username'])?>" alt="">发起人：<?=h($p['owner_nickname']?:$p['owner_username'])?></span><b>查看项目 →</b></div></a><?php endforeach;?></section>
<section class="plan-empty" data-empty <?=$projects?'hidden':''?>>还没有项目。通过成员验证后可以创建第一个建筑计划。</section>
<?php if($user&&auth_is_site_admin()):?><section class="plan-create" data-create hidden><div class="plan-create-panel" role="dialog" aria-modal="true"><button class="plan-close" data-create-close aria-label="关闭">×</button><p class="plans-kicker">NEW PROJECT</p><h2>新建项目</h2><form data-create-form><label>项目名称<input name="name" required maxlength="80"></label><label>一句话说明<input name="description" maxlength="240"></label><label>详细说明<textarea name="about" maxlength="10000"></textarea></label><p class="plan-form-error" data-error></p><button class="plans-primary" type="submit">创建并进入</button></form></div></section><?php endif;?></main>
<footer class="site-footer"><div class="shell"><span>示例服务器 · <a href="about.php">关于计划表</a></span><div class="filing"></div></div></footer>
<script>(function(){let mode='all';const search=document.querySelector('[data-search]'),cards=[...document.querySelectorAll('.plan-card')],empty=document.querySelector('[data-empty]');function apply(){let n=0,q=search.value.trim().toLowerCase();cards.forEach(c=>{let show=(mode==='all'||c.dataset.status===mode)&&(!q||c.dataset.search.includes(q));c.hidden=!show;if(show)n++});empty.hidden=n>0}document.querySelectorAll('[data-filter]').forEach(b=>b.onclick=()=>{document.querySelectorAll('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');mode=b.dataset.filter;apply()});search.oninput=apply;const modal=document.querySelector('[data-create]');if(modal){document.querySelector('[data-create-open]').onclick=()=>modal.hidden=false;document.querySelector('[data-create-close]').onclick=()=>modal.hidden=true;modal.onclick=e=>{if(e.target===modal)modal.hidden=true};document.querySelector('[data-create-form]').onsubmit=async e=>{e.preventDefault();let body={...Object.fromEntries(new FormData(e.target)),action:'create_project',csrf_token:'<?=h($csrf)?>'},button=e.target.querySelector('[type=submit]'),error=document.querySelector('[data-error]');button.disabled=true;try{let r=await fetch('api.php',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}),v=await r.json();if(!r.ok)throw new Error(v.error||'创建失败');location.href='project.php?id='+encodeURIComponent(v.id)}catch(x){error.textContent=x.message;button.disabled=false}}}})();</script></body></html>
