pluginManagement {
    repositories {
        maven { url = 'https://maven.fabricmc.net/' }
        gradlePluginPortal()
        mavenCentral()
    }
}

rootProject.name = 'mc-site-collector'
include 'core'

def modules = [
    'fabric-26.1'
]
def selected = gradle.startParameter.projectProperties['onlyProject']
if (selected) {
    if (!modules.contains(selected)) {
        throw new GradleException("Unknown onlyProject: " + selected)
    }
    include selected
} else {
    modules.each { include it }
}